-- Suite à l'exercice 8, nous allons insérer toutes ces tables dans la
-- BDD centrale, donc nous devons nous débarasser des
--create synonym personnel for personnel@hopit;
--create synonym medecin for medecin@hopit;
--create synonym infirmiere for infirmiere@hopit;
--create synonym rattache for rattache@hopit;
--create synonym affectation for affectation@hopit;
--create synonym service for service@hopit;
